### ISSUE TITLE
Checkpoint support

### ISSUE THREAD

**Issue by roperi** [Julian-O/Instagram-API-python#2]
...In order to overcome problems like [#29](https://github.com/LevPasha/Instagram-API-python/issues/29)

A PHP-based solution can be found in [checkpoint_required #379 at mgp25/Instagram-API](https://github.com/mgp25/Instagram-API/issues/379).

**Comment by Julian-O** [comment]
Sorry, I have little idea what this means. Do you have a better description of the problem and the solution? Is it ported to Python?

**Comment by roperi** [comment]
Hi, Julian!

As far as I understand LevPasha based his Instagram-API-python on mgp25's Instagram-API (which is PHP based). 

It would be great to be able to handle errors like the "checkpoint_challenge_required" one and related ones which requires the user to verify his/her account.

Thanks

**Comment by Julian-O** [comment]
Yes, LevPasha has loosely based his solution on Instagram-API. The structure is quite different though, so the mapping between them isn't obvious.

I see that in the PHP examples, they show how a user can perform two-factor authentication.

Unfortunately, I neither have code from LevPasha that does this, an account that has 2FA, or a firm grasp on the protocol to implement this myself.

Does anyone want to make a stab?

**Comment by skawm** [comment]
Hi! indeed checkpoint support would be very useful =/

**Comment by Julian-O** [comment]
I now support 2FA. I do not know if that is the same as checkpoint support. It sounds awfully like checkpoint support is related to having your account restricted in some way.

In the absence of a clear description of the problem, and a way to replicate, I cannot even attempt to fix this. I welcome others to try.

**Comment by roperi** [comment]
@Julian-O 

Sorry if I haven't provided a clear description of the problem yet. Mainly because I haven't taken enough notes about it. Also, it didn't help me the PHP folks deleted the solutions to this and related issues from their repo. Once I'm ready to clearly explain the issue and replicate it I'll report back here. Thanks!

**Comment by Julian-O** [comment]
I've been doing a bit more reading. It seems checkpointing is required when Instagram figures out you are using an unofficial API and/or logging in from an unusual location and are worried you are spamming, so they require you to log in from your phone. The short-term solution is to log in from your phone. The long-term solution is to work out what behaviour (spamming, perhaps?) attracted their attention and avoid it
